<a href="https://colab.research.google.com/github/chetools/CHE4071_Spring2026/blob/main/TubularReactorBandBroadening.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/chetools/chetools/main/tools/che5.ipynb -O che5.ipynb
%run che5.ipynb

In [2]:
N = 2000
totV = 100. #L
V = totV/N
q=100. #L/min
cin0 = 1. #mol/L
c0 = np.full(N,cin0)
tend=1.

In [17]:
def sigmoid(x, x0=0, width=1.):
    return sp.special.expit((x-x0)/width)

def pulse(x, x1, x2, c1, c2, width=1.):
    return c1 + (c2-c1)*sigmoid(x, x0=x1, width=width) - (c2-c1)*sigmoid(x, x0=x2, width=width)

In [20]:
x = np.linspace(0,10,1000)
fig = make_subplots()
fig.add_scatter(x=x, y=pulse(x, 1., 2., 1., 4., 0.01))

In [3]:
def rhs(t, vec):
    cin = 1.2*cin0
    c = vec
    dc = np.zeros(N)
    dc[0] = q*(cin - c[0])/V
    dc[1:] = q*(c[:-1] - c[1:])/V
    return dc

In [6]:
N_times = 50
tplot = np.linspace(0,tend,N_times)
res=sp.integrate.solve_ivp(rhs, (0,tend), c0, method='Radau', dense_output=True)
c_profiles = res.sol(tplot)

In [7]:
fig = make_subplots()
for t_index in range(N_times):
    fig.add_scatter(x = np.arange(N), y = c_profiles[:, t_index])
fig

  message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  4.218e-02  1.977e-01  4.038e-01  6.933e-01
             1.092e+00  1.606e+00  2.378e+00  3.393e+00  5.292e+00
             1.000e+01]
        y: [[ 1.000e+00  1.038e+00 ...  1.200e+00  1.200e+00]
            [ 1.000e+00  1.004e+00 ...  1.200e+00  1.200e+00]
            ...
            [ 1.000e+00  1.000e+00 ...  1.200e+00  1.200e+00]
            [ 1.000e+00  1.000e+00 ...  1.200e+00  1.200e+00]]
      sol: <scipy.integrate._ivp.common.OdeSolution object at 0x7fe003e557f0>
 t_events: None
 y_events: None
     nfev: 72
     njev: 1
      nlu: 20

array([[ 0,  3,  6],
       [ 7, 10, 13],
       [14, 17, 20],
       [21, 24, 27],
       [28, 31, 34]])